version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: todo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file: 
      - .env  
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: on-failure

volumes:
  pgdata:
    driver: local